name: Simple App Deployment
on: 
    push: 
      branches: 
        - Test

jobs: 
  testdeployment:
    runs-on: ubuntu-latest
    steps: 
      - name: "Greetings"
        run: |
          echo "--- Greetings ----"
      
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create version number"
        run: |
          #echo "APP_VERSION=${RANDOM}" >> $GITHUB_ENV

          #echo ${{ env.APP_VERSION }}
      
      # - name: "Build a Docker image from the repo v1"
      #   run:  | 
      #     docker build -t theoafactor/simplewebapp:v1 frontend/

      - name: "Build a Docker image"
        run:  | 
             sudo docker build -t healerkay/books:${{ env.APP_VERSION }} frontend/

      - name: "Log into Docker Hub"
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Push to Docker Hub"
        run: |
          docker push healerkay/books:${{ env.APP_VERSION }}

         
      - name: "Announce the latest version of the deployment"
        uses: dawidd6/action-send-mail@v3
        with:
                username: taykeny94@gmail.com
                password: ${{ secrets.EMAIL_PASSWORD }}
                server_address: smtp.gmail.com
                server_port: 465
                secure: true
                subject: "New Docker Image Version for Simple Web App"
                to: "taykeny94@gmail.com"
                from: Abatan Taiwo <taykeny94@gmail.com>
                body: "New image build: ${{ env.APP_VERSION }}"
